# API version untuk resource Secret
apiVersion: v1
# Jenis resource Kubernetes
kind: Secret

# Metadata identitas secret
metadata:
  name: library-secret
  namespace: dev

# Tipe secret generik key-value
type: Opaque

# Data sensitif dalam format string (akan di-encode base64 oleh Kubernetes)
stringData:
  DB_USER: "library"
  DB_PASSWORD: "library123"
  DB_NAME: "librarydb"