# API version untuk resource ConfigMap
apiVersion: v1
# Jenis resource Kubernetes
kind: ConfigMap

# Metadata identitas resource
metadata:
  name: library-config
  namespace: prestage

# Kumpulan environment variable non-rahasia untuk aplikasi
data:
  APP_NAME: "Library Management"
  APP_ENV: "PRESTAGE"
  APP_VERSION: "v1"