# API version untuk HorizontalPodAutoscaler v2
apiVersion: autoscaling/v2
# Jenis resource autoscaling
kind: HorizontalPodAutoscaler

# Metadata identitas HPA
metadata:
  name: library-hpa
  namespace: prestage

# Aturan autoscaling untuk deployment target
spec:

  # Referensi workload yang akan di-scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: library-app

  # Batas jumlah replika minimum dan maksimum
  minReplicas: 3
  maxReplicas: 5

  # Perilaku scaling untuk menghindari flapping
  behavior:

    scaleDown:
      stabilizationWindowSeconds: 60

  # Metric yang dipakai untuk menentukan scaling
  metrics:

    - type: Resource

      resource:
        # Gunakan utilisasi CPU sebagai acuan
        name: cpu

        target:
          type: Utilization
          averageUtilization: 60