apiVersion: v1
kind: Service

metadata:
  name: library-service
  namespace: prestage

spec:
  selector:
    app: library-app

  ports:
    - port: 80
      targetPort: 5000

  type: ClusterIP
